# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-25 04:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='sessionDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('session1', models.CharField(max_length=200)),
                ('session2', models.CharField(max_length=200)),
                ('session3', models.CharField(max_length=200)),
                ('session4', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'sessiondetails',
            },
        ),
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tname', models.CharField(max_length=100)),
                ('Tage', models.IntegerField()),
                ('Tqualification', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'traineedetails',
            },
        ),
        migrations.AddField(
            model_name='sessiondetails',
            name='tid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Task.Trainee'),
        ),
    ]
