# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-26 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiondetails',
            name='tid',
            field=models.ForeignKey(on_delete='id', to='Task.Trainee', to_field='user'),
        ),
    ]
