# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-07 04:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0007_evaluation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainee',
            old_name='Tage',
            new_name='Age',
        ),
        migrations.RenameField(
            model_name='trainee',
            old_name='Tname',
            new_name='Full_Name',
        ),
        migrations.RenameField(
            model_name='trainee',
            old_name='Tqualification',
            new_name='Qualification',
        ),
    ]
